### ISSUE TITLE
is there any better extension

### ISSUE THREAD

**Issue by foodornt** [pantharshit00/coc-prisma#3]
like can I use graphql with some kind of config file and make it work?

**Comment by foodornt** [comment]
why is this thing not working I just installed the server

**Comment by pantharshit00** [comment]
> like can I use graphql with some kind of config file and make it work?

Hello, this extension is meant for Prisma schema files(https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema). It exposes the prisma language server in (n)vim via CoC completion engine.

You will need to have CoC installed in order to use this: https://github.com/neoclide/coc.nvim

After that you can run `:CocInstall coc-prisma` to install this extension.

It will start showing you autocompletion and validation like so:
![image](https://user-images.githubusercontent.com/22195362/94980052-21ec9580-0544-11eb-8e8e-938751dce9b8.png)

**Comment by pantharshit00** [comment]
Regarding, alternatives, there is no alternative extension for Prisma in vim ecosystem right now. 

You can use the official vscode extension if you also use vscode: https://marketplace.visualstudio.com/items?itemName=Prisma.prisma


If you are looking for syntax highlighting in vim, this extension won't do that, you will need this other extension that I wrote: https://github.com/pantharshit00/vim-prisma

**Comment by foodornt** [comment]
Thank you for the detailed response, does this extension support prisma 1 datamodels?

**Comment by pantharshit00** [comment]
You can use vim-graphql if you want Prisma 1 support: https://github.com/jparise/vim-graphql#syntax-highlighting
